/****************************************************************************
**
** Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
** All rights reserved.
** Contact: Nokia Corporation (qt-info@nokia.com)
**
** This file is part of the Qt Mobility Components.
**
** $QT_BEGIN_LICENSE:LGPL$
** No Commercial Usage
** This file contains pre-release code and may not be distributed.
** You may use this file in accordance with the terms and conditions
** contained in the Technology Preview License Agreement accompanying
** this package.
**
** GNU Lesser General Public License Usage
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.LGPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Nokia gives you certain additional
** rights.  These rights are described in the Nokia Qt LGPL Exception
** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
**
** If you have questions regarding the use of this file, please contact
** Nokia at qt-info@nokia.com.
**
**
**
**
**
**
**
**
** $QT_END_LICENSE$
**
****************************************************************************/

#include "qorganizeriteminstancefetchrequest.h"
#include "qorganizeritemrequests_p.h"

QTM_BEGIN_NAMESPACE

/*!
  \class QOrganizerItemInstanceFetchRequest
  \brief The QOrganizerItemInstanceFetchRequest class allows a client to asynchronously
    request occurrences generated by a recurring item.
  \inmodule QtOrganizer

  For a QOrganizerItemInstanceFetchRequest, the resultsAvailable() signal will be emitted when the resultant
  organizer items (which may be retrieved by calling items()), are updated, as well as if
  the overall operation error (which may be retrieved by calling error()) is updated.

  \ingroup organizer-requests
 */

/*! Constructs a new organizer item fetch request whose parent is the specified \a parent */
QOrganizerItemInstanceFetchRequest::QOrganizerItemInstanceFetchRequest(QObject* parent)
    : QOrganizerItemAbstractRequest(new QOrganizerItemInstanceFetchRequestPrivate, parent)
{
}

/*! Sets the generator item, whose occurrences are to be fetched. */
void QOrganizerItemInstanceFetchRequest::setGenerator(const QOrganizerItem &item)
{
    Q_D(QOrganizerItemInstanceFetchRequest);
    d->m_generator = item;
}

/*! Sets the start date of the request to \a date.  All occurrences fetched will have a date on or
 * after \a date. */
void QOrganizerItemInstanceFetchRequest::setStartDate(const QDateTime &date)
{
    Q_D(QOrganizerItemInstanceFetchRequest);
    d->m_startDate = date;
}

/*! Sets the end period of the request to \a date.  All occurrences fetched will have a date on or
 * before \a date. */
void QOrganizerItemInstanceFetchRequest::setEndDate(const QDateTime &date)
{
    Q_D(QOrganizerItemInstanceFetchRequest);
    d->m_endDate = date;
}

/*! Sets the maximum number of items to fetch to \a maxCount. */
void QOrganizerItemInstanceFetchRequest::setCountLimit(int maxCount)
{
    Q_D(QOrganizerItemInstanceFetchRequest);
    d->m_countLimit = maxCount;
}

/*! Returns the generator item, whose occurrences are to be fetched. */
QOrganizerItem QOrganizerItemInstanceFetchRequest::generator() const
{
    Q_D(const QOrganizerItemInstanceFetchRequest);
    return d->m_generator;
}

/*! Returns the start date of the request. */
QDateTime QOrganizerItemInstanceFetchRequest::startDate() const
{
    Q_D(const QOrganizerItemInstanceFetchRequest);
    return d->m_startDate;
}

/*! Returns the end date of the request. */
QDateTime QOrganizerItemInstanceFetchRequest::endDate() const
{
    Q_D(const QOrganizerItemInstanceFetchRequest);
    return d->m_endDate;
}

/*! Returns the maximum number of items to fetch. */
int QOrganizerItemInstanceFetchRequest::countLimit() const
{
    Q_D(const QOrganizerItemInstanceFetchRequest);
    return d->m_countLimit;
}

/*! Returns the list of organizer items retrieved by this request */
QList<QOrganizerItem> QOrganizerItemInstanceFetchRequest::items() const
{
    // XXX TODO: this should be "itemInstances()" instead
    Q_D(const QOrganizerItemInstanceFetchRequest);
    return d->m_organizeritems;
}

#include "moc_qorganizeriteminstancefetchrequest.cpp"

QTM_END_NAMESPACE
