######################################################################
# Automatically generated by qmake (2.01a) Wed 18. Nov 17:41:48 2009
######################################################################

CONFIG -= qt
TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

INCLUDEPATH += $$APP_LAYER_SYSTEMINCLUDE
LIBS += -letel -letelmm
