DEFINES+=QMESSAGING_OPTIONAL QMESSAGING_OPTIONAL_FOLDER

win32 {

    EXAMPLES_INSTALL_ROOT=$$MESSAGING_INSTALL_ROOT
    LIBRARIES_INSTALL_ROOT=$$MESSAGING_INSTALL_ROOT
    TESTS_INSTALL_ROOT=$$MESSAGING_INSTALL_ROOT

    debug{
        OUTPREFIX=Debug
    } else {
        OUTPREFIX=Release
    }

} else {
    EXAMPLES_INSTALL_ROOT=$$MESSAGING_INSTALL_ROOT/bin
    LIBRARIES_INSTALL_ROOT=$$MESSAGING_INSTALL_ROOT/lib
    TESTS_INSTALL_ROOT=$$MESSAGING_INSTALL_ROOT/tests
}

