######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 19 12:34:42 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

message($$(QMF_INCLUDEDIR)  - $$(QMF_LIBDIR))

# QMF headers must be located at $QMF_INCLUDEDIR
INCLUDEPATH += $$(QMF_INCLUDEDIR) $$(QMF_INCLUDEDIR)/support

# QMF libraries must be located at $QMF_LIBDIR
LIBS += -L $$(QMF_LIBDIR) -lqtopiamail
QMAKE_RPATHDIR+= $$(QMF_LIBDIR)

# Input
SOURCES += main.cpp
