#!/bin/bash

if [ -z "$1" ]; then
echo "usage: $0 <contact-uid> <imaccount-uid> <im-id> <nickname> <imPresence> <statusMessage> <protocol> <nameGiven> <nameFamily>"
exit 1
fi
echo "create nco:IMAccount"
tracker-sparql -u -q "
INSERT 
{ 
<http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$2> 
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> 
<http://www.semanticdesktop.org/ontologies/2007/03/22/nco#IMAccount>
}
"

echo "create nco:IMContact"
tracker-sparql -u -q "INSERT
{
<$1>
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
<http://www.semanticdesktop.org/ontologies/2007/03/22/nco#IMContact>
}
"
echo "create nco:IMContact"
tracker-sparql --update --query "INSERT {
	    <$1> a nco:IMContact;
	    nco:contactUID '$2';
	    nco:imContactId '$3';
	    nco:imContactNickname '$4';
	    nco:imContactPresence $5;
	    nco:imContactStatusMessage '$6';
	    nco:fromIMAccount <http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$2>;
	    nco:imContactCapability <bogus>
}"
echo "update nco:IMContact"
tracker-sparql --update --query "INSERT {
        <$1> a nco:IMContact;
	    nco:nameGiven '$8';
        nco:nameFamily '$9'
}
"
