#!/bin/bash

if [ -z "$1" ]; then
echo "usage: $0 <imaccount-uid> <imPresence>"
exit 1
fi
tracker-sparql --update --query "
DELETE { <$1> nco:imContactPresence ?status }
WHERE { <$1> nco:imContactPresence ?status }
INSERT { <$1> nco:imContactPresence $2 }
"
