#!/bin/sh

if [ -z "$1" ]; then
echo "usage: $0 <imaccount-uid> <imPresence>"
exit 1
fi

tracker-sparql --update --query "
DELETE { <http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$1> nco:imPresence ?status }
 WHERE { <http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$1> nco:imPresence ?status }
INSERT { <http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$1>  nco:imPresence $2 }
"
