#!/bin/bash

if [ -z "$1" ]; then
echo "usage: $0 <IMAddress-uri> <imPresence>"
exit 1
fi
tracker-sparql --update --query "
DELETE { <$1> nco:imPresence ?status }
WHERE { <$1> nco:imPresence ?status }
INSERT { <$1> nco:imPresence $2 }
"
