# #####################################################################
# Telephony Mobility API
# #####################################################################

HEADERS +=  maemo/qtelephonycalllist_maemo_p.h \
            maemo/qtelephonycallinfo_maemo_p.h \
            maemo/sharedpointer.h \
            maemo/clientbase.h \
            maemo/clientbaseobserver.h \
            maemo/clientadaptor.h \
            maemo/clientobserveradaptor.h \
            maemo/constants.h \
            maemo/types.h \
            maemo/dbusproxy.h \
            maemo/statelessdbusproxy.h \
            maemo/statefulldbusproxy.h \
            maemo/readyobject.h \
            maemo/feature.h \
            maemo/features.h \
            maemo/readinesshelper.h \
            maemo/pendingcomposite.h \
            maemo/pendingfailure.h \
            maemo/pendingoperation.h \
            maemo/pendingready.h \
            maemo/pendingsuccess.h \
            maemo/pendingvoid.h \
            maemo/connection.h \
            maemo/channel.h \
            maemo/accountmanager.h \
            maemo/account.h \
            maemo/interfaces/itypes.h \
            maemo/interfaces/iaccountmanager.h \
            maemo/interfaces/iaccount.h \
            maemo/interfaces/iaccountavatar.h \
            maemo/interfaces/ichanneldispatchoperation.h \
            maemo/interfaces/ichanneldispatcher.h \
            maemo/interfaces/ichannelrequest.h \
            maemo/interfaces/ichannel.h \
            maemo/interfaces/ichannelcallstate.h \
            maemo/interfaces/ichannelchatstate.h \
            maemo/interfaces/ichanneldtmf.h \
            maemo/interfaces/ichannelgroup.h \
            maemo/interfaces/ichannelhold.h \
            maemo/interfaces/ichannelmediasignalling.h \
            maemo/interfaces/ichannelmessages.h \
            maemo/interfaces/ichannelpassword.h \
            maemo/interfaces/ichanneltube.h \
            maemo/interfaces/ichanneltypecontactlist.h \
            maemo/interfaces/ichanneltypefiletransfer.h \
            maemo/interfaces/ichanneltyperoomlist.h \
            maemo/interfaces/ichanneltypestreamedmedia.h \
            maemo/interfaces/ichanneltypestreamtube.h \
            maemo/interfaces/ichanneltypetext.h \
            maemo/interfaces/ichanneltypetubes.h \
            maemo/interfaces/iclient.h \
            maemo/interfaces/iclientapprover.h \
            maemo/interfaces/iclienthandler.h \
            maemo/interfaces/iclientrequests.h \
            maemo/interfaces/iclientobserver.h \
            maemo/interfaces/iconnectionmanager.h \
            maemo/interfaces/iconnection.h \
            maemo/interfaces/iconnectionaliasing.h \
            maemo/interfaces/iconnectionavatars.h \
            maemo/interfaces/iconnectionbalance.h \
            maemo/interfaces/iconnectioncapabilities.h \
            maemo/interfaces/iconnectioncontactcapabilities.h \
            maemo/interfaces/iconnectioncontactinfo.h \
            maemo/interfaces/iconnectioncontacts.h \
            maemo/interfaces/iconnectionlocation.h \
            maemo/interfaces/iconnectionmanager.h \
            maemo/interfaces/iconnectionpresence.h \
            maemo/interfaces/iconnectionrequests.h \
            maemo/interfaces/iconnectionsimplepresence.h \
            maemo/interfaces/iabstract.h

SOURCES +=  maemo/qtelephonycalllist_maemo.cpp \
            maemo/qtelephonycallinfo_maemo_p.cpp \
            maemo/clientbase.cpp \
            maemo/clientbaseobserver.cpp \
            maemo/types.cpp \
            maemo/clientadaptor.cpp \
            maemo/clientobserveradaptor.cpp \
            maemo/dbusproxy.cpp \
            maemo/statelessdbusproxy.cpp \
            maemo/statefulldbusproxy.cpp \
            maemo/readyobject.cpp \
            maemo/feature.cpp \
            maemo/readinesshelper.cpp \
            maemo/pendingcomposite.cpp \
            maemo/pendingoperation.cpp \
            maemo/pendingready.cpp \
            maemo/pendingvoid.cpp \
            maemo/connection.cpp \
            maemo/channel.cpp \
            maemo/accountmanager.cpp \
            maemo/account.cpp \
            maemo/interfaces/itypes.cpp \
            maemo/interfaces/iaccount.cpp \
            maemo/interfaces/iaccountavatar.cpp \
            maemo/interfaces/iaccountmanager.cpp \
            maemo/interfaces/ichannel.cpp \
            maemo/interfaces/ichannelcallstate.cpp \
            maemo/interfaces/ichannelchatstate.cpp \
            maemo/interfaces/ichanneldtmf.cpp \
            maemo/interfaces/ichannelgroup.cpp \
            maemo/interfaces/ichannelhold.cpp \
            maemo/interfaces/ichannelmediasignalling.cpp \
            maemo/interfaces/ichannelmessages.cpp \
            maemo/interfaces/ichannelpassword.cpp \
            maemo/interfaces/ichanneltube.cpp \
            maemo/interfaces/ichanneltypecontactlist.cpp \
            maemo/interfaces/ichanneltypefiletransfer.cpp \
            maemo/interfaces/ichanneltyperoomlist.cpp \
            maemo/interfaces/ichanneltypestreamedmedia.cpp \
            maemo/interfaces/ichanneltypestreamtube.cpp \
            maemo/interfaces/ichanneltypetext.cpp \
            maemo/interfaces/ichanneltypetubes.cpp \
            maemo/interfaces/ichanneldispatcher.cpp \
            maemo/interfaces/ichanneldispatchoperation.cpp \
            maemo/interfaces/ichannelrequest.cpp \
            maemo/interfaces/iclient.cpp \
            maemo/interfaces/iclientapprover.cpp \
            maemo/interfaces/iclienthandler.cpp \
            maemo/interfaces/iclientrequests.cpp \
            maemo/interfaces/iclientobserver.cpp \
            maemo/interfaces/iconnection.cpp \
            maemo/interfaces/iconnectionaliasing.cpp \
            maemo/interfaces/iconnectionavatars.cpp \
            maemo/interfaces/iconnectionbalance.cpp \
            maemo/interfaces/iconnectioncapabilities.cpp \
            maemo/interfaces/iconnectioncontactcapabilities.cpp \
            maemo/interfaces/iconnectioncontactinfo.cpp \
            maemo/interfaces/iconnectioncontacts.cpp \
            maemo/interfaces/iconnectionlocation.cpp \
            maemo/interfaces/iconnectionpresence.cpp \
            maemo/interfaces/iconnectionrequests.cpp \
            maemo/interfaces/iconnectionsimplepresence.cpp \
            maemo/interfaces/iconnectionmanager.cpp \
            maemo/interfaces/iabstract.cpp

