/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a accessrequestor_adaptor_p.h:accessrequestor_adaptor.cpp com.nokia.nfc.AccessRequestor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "accessrequestor_adaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AccessRequestorAdaptor
 */

AccessRequestorAdaptor::AccessRequestorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AccessRequestorAdaptor::~AccessRequestorAdaptor()
{
    // destructor
}

void AccessRequestorAdaptor::AccessFailed(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call com.nokia.nfc.AccessRequestor.AccessFailed
    QMetaObject::invokeMethod(parent(), "AccessFailed", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

void AccessRequestorAdaptor::AccessGranted(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call com.nokia.nfc.AccessRequestor.AccessGranted
    QMetaObject::invokeMethod(parent(), "AccessGranted", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

