/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a accessrequestor_adaptor_p.h:accessrequestor_adaptor.cpp com.nokia.nfc.AccessRequestor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCESSREQUESTOR_ADAPTOR_P_H_1294121544
#define ACCESSREQUESTOR_ADAPTOR_P_H_1294121544

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.nfc.AccessRequestor
 */
class AccessRequestorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.nfc.AccessRequestor")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.nfc.AccessRequestor\">\n"
"    <method name=\"AccessFailed\">\n"
"      <arg direction=\"in\" type=\"o\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"AccessGranted\">\n"
"      <arg direction=\"in\" type=\"o\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AccessRequestorAdaptor(QObject *parent);
    virtual ~AccessRequestorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void AccessFailed(const QDBusObjectPath &in0, const QString &in1);
    void AccessGranted(const QDBusObjectPath &in0, const QString &in1);
Q_SIGNALS: // SIGNALS
};

#endif
