/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i meego/dbustypes_p.h -p adapter_interface_p.h:adapter_interface.cpp com.nokia.nfc.Adapter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ADAPTER_INTERFACE_P_H_1294121544
#define ADAPTER_INTERFACE_P_H_1294121544

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "meego/dbustypes_p.h"

/*
 * Proxy class for interface com.nokia.nfc.Adapter
 */
class ComNokiaNfcAdapterInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.nfc.Adapter"; }

public:
    ComNokiaNfcAdapterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComNokiaNfcAdapterInterface();

    Q_PROPERTY(bool Discovering READ discovering)
    inline bool discovering() {
        QDBusReply<QVariantMap> reply = GetProperties();
        if (!reply.isValid())
            return false;

        return reply.value().value(QLatin1String("Discovering")).toBool();
    }

    Q_PROPERTY(QString State READ state WRITE setState)
    inline QString state() {
        QDBusReply<QVariantMap> reply = GetProperties();
        if (!reply.isValid())
            return QString();

        return reply.value().value(QLatin1String("State")).toString();
    }

    inline void setState(const QString &value)
    { SetProperty(QLatin1String("State"), QDBusVariant(qVariantFromValue(value))); }

    Q_PROPERTY(QStringList TagTechnologies READ tagTechnologies)
    inline QStringList tagTechnologies()
    {
        QDBusReply<QVariantMap> reply = GetProperties();
        if (!reply.isValid())
            return QStringList();

        return reply.value().value(QLatin1String("TagTechnologies")).toStringList();
    }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> CancelAccessRequest(const QDBusObjectPath &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("CancelAccessRequest"), argumentList);
    }

    inline QDBusPendingReply<> CancelHandoverRequest(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("CancelHandoverRequest"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetProperties"), argumentList);
    }

    inline QDBusPendingReply<> RegisterUIAgent(const QDBusObjectPath &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("RegisterUIAgent"), argumentList);
    }

    inline QDBusPendingReply<> RequestAccess(const QDBusObjectPath &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("RequestAccess"), argumentList);
    }

    inline QDBusPendingReply<> RequestHandover(const QDBusObjectPath &in0, const QString &in1, const QString &in2)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1) << qVariantFromValue(in2);
        return asyncCallWithArgumentList(QLatin1String("RequestHandover"), argumentList);
    }

    inline QDBusPendingReply<> SetProperty(const QString &in0, const QDBusVariant &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("SetProperty"), argumentList);
    }

    inline QDBusPendingReply<> UnregisterUIAgent(const QDBusObjectPath &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("UnregisterUIAgent"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void PropertyChanged(const QString &in0, const QDBusVariant &in1);
    void TargetDetected(const QDBusObjectPath &in0);
    void TargetDetectionError(int in0);
    void TargetLost(const QDBusObjectPath &in0);
};

namespace com {
  namespace nokia {
    namespace nfc {
      typedef ::ComNokiaNfcAdapterInterface Adapter;
    }
  }
}
#endif
