/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i meego/dbustypes_p.h -p adapter_interface_p.h:adapter_interface.cpp com.nokia.nfc.Adapter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "adapter_interface_p.h"

/*
 * Implementation of interface class ComNokiaNfcAdapterInterface
 */

ComNokiaNfcAdapterInterface::ComNokiaNfcAdapterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComNokiaNfcAdapterInterface::~ComNokiaNfcAdapterInterface()
{
}

