/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i meego/dbustypes_p.h -p device_interface_p.h:device_interface.cpp com.nokia.nfc.Device.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DEVICE_INTERFACE_P_H_1294121544
#define DEVICE_INTERFACE_P_H_1294121544

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "meego/dbustypes_p.h"

/*
 * Proxy class for interface com.nokia.nfc.Device
 */
class ComNokiaNfcDeviceInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.nfc.Device"; }

public:
    ComNokiaNfcDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComNokiaNfcDeviceInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QVariantMap> Services()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Services"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace nokia {
    namespace nfc {
      typedef ::ComNokiaNfcDeviceInterface Device;
    }
  }
}
#endif
