/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a llcprequestor_adaptor_p.h:llcprequestor_adaptor.cpp com.nokia.nfc.LLCPRequestor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "llcprequestor_adaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class LLCPRequestorAdaptor
 */

LLCPRequestorAdaptor::LLCPRequestorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

LLCPRequestorAdaptor::~LLCPRequestorAdaptor()
{
    // destructor
}

void LLCPRequestorAdaptor::Accept(const QDBusObjectPath &in0, const QDBusVariant &in1, const QDBusVariant &in2, int in3)
{
    // handle method call com.nokia.nfc.LLCPRequestor.Accept
    QMetaObject::invokeMethod(parent(), "Accept", Q_ARG(QDBusObjectPath, in0), Q_ARG(QDBusVariant, in1), Q_ARG(QDBusVariant, in2), Q_ARG(int, in3));
}

void LLCPRequestorAdaptor::Connect(const QDBusObjectPath &in0, const QDBusVariant &in1, const QDBusVariant &in2, int in3)
{
    // handle method call com.nokia.nfc.LLCPRequestor.Connect
    QMetaObject::invokeMethod(parent(), "Connect", Q_ARG(QDBusObjectPath, in0), Q_ARG(QDBusVariant, in1), Q_ARG(QDBusVariant, in2), Q_ARG(int, in3));
}

void LLCPRequestorAdaptor::Socket(const QDBusObjectPath &in0, const QDBusVariant &in1, const QDBusVariant &in2, int in3)
{
    // handle method call com.nokia.nfc.LLCPRequestor.Socket
    QMetaObject::invokeMethod(parent(), "Socket", Q_ARG(QDBusObjectPath, in0), Q_ARG(QDBusVariant, in1), Q_ARG(QDBusVariant, in2), Q_ARG(int, in3));
}

