/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i meego/dbustypes_p.h -p manager_interface_p.h:manager_interface.cpp com.nokia.nfc.Manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MANAGER_INTERFACE_P_H_1294121544
#define MANAGER_INTERFACE_P_H_1294121544

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "meego/dbustypes_p.h"

/*
 * Proxy class for interface com.nokia.nfc.Manager
 */
class ComNokiaNfcManagerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.nfc.Manager"; }

public:
    ComNokiaNfcManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComNokiaNfcManagerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusObjectPath> DefaultAdapter()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("DefaultAdapter"), argumentList);
    }

    inline QDBusPendingReply<QDBusObjectPath> FindAdapter(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("FindAdapter"), argumentList);
    }

    inline QDBusPendingReply<QList<QDBusObjectPath> > ListAdapters()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ListAdapters"), argumentList);
    }

    inline QDBusPendingReply<> RegisterNDEFHandler(const QString &in0, const QString &in1, const QDBusObjectPath &in2, const QString &in3, const QString &in4)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1) << qVariantFromValue(in2) << qVariantFromValue(in3) << qVariantFromValue(in4);
        return asyncCallWithArgumentList(QLatin1String("RegisterNDEFHandler"), argumentList);
    }

    inline QDBusPendingReply<> UnregisterNDEFHandler(const QString &in0, const QString &in1, const QDBusObjectPath &in2)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1) << qVariantFromValue(in2);
        return asyncCallWithArgumentList(QLatin1String("UnregisterNDEFHandler"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void AdapterAdded(const QDBusObjectPath &in0);
    void AdapterRemoved(const QDBusObjectPath &in0);
    void DefaultAdapterChanged(const QDBusObjectPath &in0);
};

namespace com {
  namespace nokia {
    namespace nfc {
      typedef ::ComNokiaNfcManagerInterface Manager;
    }
  }
}
#endif
