/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a ndefhandler_adaptor_p.h:ndefhandler_adaptor.cpp com.nokia.nfc.NDEFHandler.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NDEFHANDLER_ADAPTOR_P_H_1294121544
#define NDEFHANDLER_ADAPTOR_P_H_1294121544

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.nfc.NDEFHandler
 */
class NDEFHandlerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.nfc.NDEFHandler")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.nfc.NDEFHandler\">\n"
"    <method name=\"NDEFData\">\n"
"      <arg direction=\"in\" type=\"o\"/>\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NDEFHandlerAdaptor(QObject *parent);
    virtual ~NDEFHandlerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void NDEFData(const QDBusObjectPath &in0, const QByteArray &in1);
Q_SIGNALS: // SIGNALS
};

#endif
