/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a ndefhandler_adaptor_p.h:ndefhandler_adaptor.cpp com.nokia.nfc.NDEFHandler.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ndefhandler_adaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class NDEFHandlerAdaptor
 */

NDEFHandlerAdaptor::NDEFHandlerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

NDEFHandlerAdaptor::~NDEFHandlerAdaptor()
{
    // destructor
}

void NDEFHandlerAdaptor::NDEFData(const QDBusObjectPath &in0, const QByteArray &in1)
{
    // handle method call com.nokia.nfc.NDEFHandler.NDEFData
    QMetaObject::invokeMethod(parent(), "NDEFData", Q_ARG(QDBusObjectPath, in0), Q_ARG(QByteArray, in1));
}

