/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i meego/dbustypes_p.h -p tag_interface_p.h:tag_interface.cpp com.nokia.nfc.Tag.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef TAG_INTERFACE_P_H_1294121544
#define TAG_INTERFACE_P_H_1294121544

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "meego/dbustypes_p.h"

/*
 * Proxy class for interface com.nokia.nfc.Tag
 */
class ComNokiaNfcTagInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.nfc.Tag"; }

public:
    ComNokiaNfcTagInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComNokiaNfcTagInterface();

    Q_PROPERTY(uint Size READ size)
    inline uint size()
    { return qvariant_cast< uint >(GetProperties().value().value(QLatin1String("Size"))); }

    Q_PROPERTY(QString Technology READ technology)
    inline QString technology()
    { return qvariant_cast< QString >(GetProperties().value().value(QLatin1String("Technology"))); }

    Q_PROPERTY(QByteArray UID READ uID)
    inline QByteArray uID()
    { return qvariant_cast< QByteArray >(GetProperties().value().value(QLatin1String("UID"))); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetProperties"), argumentList);
    }

    inline QDBusPendingReply<QList<QByteArray> > ReadNDEFData()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ReadNDEFData"), argumentList);
    }

    inline QDBusPendingReply<> SetProperty(const QString &in0, const QDBusVariant &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("SetProperty"), argumentList);
    }

    inline QDBusPendingReply<> WriteNDEFData(const QList<QByteArray> &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("WriteNDEFData"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void PropertyChanged(const QString &in0, const QDBusVariant &in1);
};

namespace com {
  namespace nokia {
    namespace nfc {
      typedef ::ComNokiaNfcTagInterface Tag;
    }
  }
}
#endif
