#ifndef DATABASEMANAGERSERVER_GLOBAL_H
#define DATABASEMANAGERSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEMANAGERSERVER_LIBRARY)
#  define DATABASEMANAGERSERVER_EXPORT Q_DECL_EXPORT
#else
#  if defined(DATABASEMANAGERSERVER_NO_LIBRARY)
#    define DATABASEMANAGERSERVER_EXPORT
#  else
#    define DATABASEMANAGERSERVER_EXPORT Q_DECL_IMPORT
#  endif
#endif

#endif // DATABASEMANAGERSERVER_GLOBAL_H
