######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 20 12:56:56 2010
######################################################################

TEMPLATE = app
TARGET = sfwipcclient
INCLUDEPATH += ../../src/serviceframework
INCLUDEPATH += ../../src/serviceframework/ipc

QT+=gui

include(../examples.pri)

CONFIG += mobility
MOBILITY = serviceframework

# Input
SOURCES += main.cpp
