#!/bin/bash

if [ -z "$1" ]; then
echo "usage: $0 <contact-uid> <imaccount-uid> <im-id> <nickname> <imPresence> <statusMessage> <protocol> <nameGiven> <nameFamily>"
exit 1
fi
echo "create nco:IMAccount"
tracker-sparql -u -q "
INSERT 
{ 
<http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$2> 
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> 
<http://www.semanticdesktop.org/ontologies/2007/03/22/nco#IMAccount>
}
"

echo "Update nco:IMAccount"
tracker-sparql --update --query "INSERT {
	<http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$2> a nco:IMAccount;
	    nco:imID '$3';
	    nco:imNickname '$4';
	    nco:imPresence $5;
	    nco:imStatusMessage '$6';
	    nco:imProtocol '$7'
}
"
echo "create nco:IMContact"
tracker-sparql -u -q "INSERT
{
<contact:$1>
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
<http://www.semanticdesktop.org/ontologies/2007/03/22/nco#IMContact>
}
"
echo "update nco:IMContact"
tracker-sparql --update --query "INSERT {
        <contact:$1> a nco:IMContact;
            nco:contactUID $1;
	    nco:nameGiven '$8';
	    nco:hasIMAccount <http://www.sopranolive.org/backends/tracker/generated_unique_id/105323876#$2>;
            nco:nameFamily '$9'
}
"
