######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 15 10:31:56 2009
######################################################################

target.path = /usr/lib/libqtlocation-tests
INSTALLS += target
TEMPLATE = app
TARGET = demoapp
DEPENDPATH += .
MOC_DIR = .moc
OBJECTS_DIR = .obj
INCLUDEPATH += .
INCLUDEPATH += ../../src

QMAKE_CXXFLAGS += -g -Wall
# QT -= gui
# QT += network

LIBS += -L../../src -lQtLocation

# Input
HEADERS += controlpanel.h location.h
SOURCES += controlpanel.cpp location.cpp main.cpp 

QMAKE_DISTCLEAN += -r .moc .obj
