######################################################################
# Automatically generated by qmake (2.01a) Wed 18. Nov 17:41:48 2009
######################################################################

CONFIG -= qt
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += $$MW_LAYER_SYSTEMINCLUDE
INCLUDEPATH += $${EPOCROOT}epoc32\include\LBTHeaders

# Input
SOURCES += main.cpp

LIBS += -llbt
