######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 11 13:18:41 2009
######################################################################

SOURCES += main.cpp
TARGET = lackey
INCLUDEPATH += ../../../../context
DEPENDPATH += ../../../../context
QT = core network

CONFIG+= testcase

include(../../../../common.pri)

qtAddLibrary(QtPublishSubscribe)

