######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 11 13:18:41 2009
######################################################################

SOURCES += main.cpp
TARGET = lackey
INCLUDEPATH += ../../../../src/publishsubscribe
DEPENDPATH += ../../../../src/publishsubscribe
QT = core network

CONFIG+= testcase

include(../../../../common.pri)

CONFIG += mobility
MOBILITY = publishsubscribe

