#ifndef SETTINGSMANAGER_GLOBAL_H
#define SETTINGSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XQSETTINGSMANAGER_LIBRARY)
#  define XQSETTINGSMANAGER_EXPORT Q_DECL_EXPORT
#else
#  if defined(XQSETTINGSMANAGER_NO_LIBRARY)
#    define XQSETTINGSMANAGER_EXPORT
#  else
#    define XQSETTINGSMANAGER_EXPORT Q_DECL_IMPORT
#  endif
#endif

#endif // SETTINGSMANAGER_GLOBAL_H
